
name: Build and publish a docker image

on:
  push:
    branches: [ master ]

jobs:
  docker_publish:
    name: Push Docker image to GitHub container repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: request2/docker-base
          github_token: ${{ secrets.GITHUB_TOKEN }}
